<?xml version="1.0"?>
<robot name="koala_wheel" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="caster" params="prefix x_reflect">
    <link name="${prefix}_link">
        <visual>
        <material name="Gray"/>
        <geometry>
            <sphere radius="${wheel_zoff}"/>
        </geometry>
        </visual>
        <xacro:sphere_inertia m="${caster_mass}" r="${wheel_zoff}"/>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_zoff}"/>
            </geometry>
        </collision>
    </link>

    <joint name="${prefix}_joint" type="fixed">
        <parent link="base_link"/>
        <child link="${prefix}_link"/>
        <origin xyz="${x_reflect*(base_radius-wheel_zoff-caster_xoff)} 0.0 ${-(base_length/2)}" rpy="0 0 0"/>
    </joint>
      <!-- Gazebo simulation -->
    <gazebo reference="${prefix}_link">
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
        <kp value="10000000.0" />
        <kd value="100.0" />
        <fdir1 value="0 0 1"/>
    </gazebo>
  </xacro:macro>
</robot>
