<?xml version="1.0"?>
<robot name="koala_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find koala_description)/urdf/macros.xacro" />
  <xacro:include filename="$(find koala_description)/urdf/wheel.xacro" />
  <xacro:include filename="$(find koala_description)/urdf/colors.xacro" />
  <xacro:include filename="$(find koala_description)/urdf/lidar.xacro" />
  <xacro:include filename="$(find koala_description)/urdf/IMU.xacro" />

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.194"/>
  <xacro:property name="base_length" value="0.200"/>
  <xacro:property name="base_height" value="0.081"/>
  <xacro:property name="base_mass" value="2.84"/>

  <xacro:property name="wheel_radius" value="0.042"/>
  <xacro:property name="wheel_width" value="0.020"/>
  <xacro:property name="wheel_ygap" value="0.00"/>
  <xacro:property name="wheel_zoff" value="-0.021"/>
  <xacro:property name="wheel_xoff" value="${wheel_radius}"/>
  <xacro:property name="wheel_mass" value="0.50"/>

  <xacro:property name="caster_xoff" value="0.00"/> <!-- distance between edge of caster to edge of base-->
  <xacro:property name="caster_mass" value="0.05"/>

<!-- Koala base :) -->
  <link name="body_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="Red"/>
    </visual>
    <xacro:box_inertia m="${base_mass}" w="${base_length}" h="${base_width}" d="${base_height}"/> 
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      
    </collision>
  </link>

<!-- Koala Footprint-->
  <link name="base_link"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body_link"/>
    <origin xyz="0.0 0.0 ${(wheel_radius-wheel_zoff)}" rpy="0 0 0"/>
  </joint> 

<!-- Koala Wheels -->
  <xacro:wheel prefix="wheel_left_front" x_reflect="1" y_reflect="1" />
  <xacro:wheel prefix="wheel_right_front" x_reflect="1" y_reflect="-1" />
  <xacro:wheel prefix="wheel_left_rear" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="wheel_right_rear" x_reflect="-1" y_reflect="-1" />


  <!-- Koala lidar -->
  <xacro:lidar parent="body_link" x_pos="0.0" y_pos="0.0" z_pos="${base_height/2}" />

  <!-- Koala IMU -->
  <xacro:IMU parent="body_link" x_pos="0.0" y_pos="0.0" z_pos="${0}" />

  <!-- Gazebo simulation -->
  <gazebo>
    <plugin name='skid_steer_drive' filename='libgazebo_ros_diff_drive.so'>
    
      <update_rate>500</update_rate>
      <num_wheel_pairs>2</num_wheel_pairs>

      <left_joint>wheel_left_front_joint</left_joint>
      <right_joint>wheel_right_front_joint</right_joint>

      <left_joint>wheel_left_rear_joint</left_joint>
      <right_joint>wheel_right_rear_joint</right_joint>
      
      <wheel_separation>${base_width+2*wheel_ygap+wheel_width}</wheel_separation>
      <wheel_separation>${base_width+2*wheel_ygap+wheel_width}</wheel_separation>

      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>

      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>body_link</robot_base_frame>
    </plugin>
  </gazebo>
</robot>


