<?xml version="1.0"?>
<robot name="koala_lidar" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- The lidar macro is defined here -->
<xacro:property name="radius_lidar" value="0.04"/>
<xacro:property name="height_lidar" value="0.04"/>
<!-- The macro lidar is defined here -->
    <xacro:macro name="lidar" params="parent x_pos y_pos z_pos ">
        <link name="lidar_link">
            <visual>
            <geometry>
                <cylinder radius="${radius_lidar}" length="${height_lidar}"/>
            </geometry>
            </visual>
            <!-- Inertia properties -->
            <cylinder radius="${radius_lidar}" length="${height_lidar}"/>
            <!-- Collision properties -->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius_lidar}" length="${height_lidar}"/>
                </geometry>
            </collision>
        </link>
        <!-- Joint properties -->
        <joint name="lidar_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="lidar_link"/>
            <origin xyz="${x_pos} ${y_pos} ${z_pos+height_lidar/2}" rpy="0 0 0"/>
        </joint>
        
        <!-- lidar properties -->
        <gazebo reference="lidar_link">
            <sensor name="koala_lidar" type="ray">
                <always_on>true</always_on>
                <update_rate>5</update_rate>
                <pose>0 0 0 0 0 0</pose>
                <ray>
                    <scan>
                        <horizontal>
                        <samples>1600</samples>
                        <resolution>1</resolution>
                        <min_angle>-${pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.2</min>
                        <max>12</max>
                        <resolution>0.03</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.05</stddev>
                    </noise>
                </ray>
                <plugin name="lidar" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <argument>~/out:=scan</argument>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                    <frame_name>lidar_link</frame_name>
                </plugin>
            </sensor>
            <!-- Material properties-->
            <material>Gazebo/Purple</material>
        </gazebo>
    </xacro:macro>
</robot>