<?xml version="1.0"?>
<robot name="koala_wheel" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
  <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" roll="${pi/2}"/>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="body_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*(base_length/2-wheel_xoff)} ${y_reflect*(base_width/2+wheel_ygap+wheel_width/2)} ${-base_height/2-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="1.5" velocity="24.0" />
      <dynamics damping="0.001" friction="0.001" />
    </joint>

  <gazebo reference="${prefix}_link">
    <collision>
          <surface>
            <friction>
              <ode>
                <mu>1</mu>
                <mu2>1</mu2>
                <slip1>0.035</slip1>
                <slip2>0</slip2>
                <fdir1>0 0 1</fdir1>
              </ode>
            </friction>
          </surface>
        </collision>
      <mu1 value="0.50"/>
      <mu2 value="3.0"/>
      <kp  value="10000000.0" />
      <kd  value="100.0" />
      <fdir1 value="0 0 1"/>
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>
</robot>