amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"  # Zmieniono z "base_footprint" - używa się base_link zamiast base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0  # Zmieniono z 100.0 - brak ograniczenia zasięgu lasera zamiast 100m
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 70  # Zwiększono z 60 - więcej promieni lasera do przetwarzania
    max_particles: 1000  # Zmniejszono z 2000 - mniej cząstek do oszczędności mocy obliczeniowej
    min_particles: 50  # Zmniejszono z 500 - mniej minimalnych cząstek
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.3  # Zwiększono z 0.2 - większy próg kąta do aktualizacji
    update_min_d: 0.2  # Zmniejszono z 0.25 - mniejszy próg odległości do aktualizacji
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map  # DODANO - określa temap mapy
    set_initial_pose: false  # DODANO - nie ustawiaj pozycji początkowej automatycznie
    always_reset_initial_pose: false  # DODANO - nie resetuj pozycji zawsze
    first_map_only: false  # DODANO - nie używaj tylko pierwszej mapy
    initial_pose:  # DODANO - pozycja początkowa robota
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 1.0

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw  # Zmieniono z costmap_topic - nowa nazwa topiku lokalnej mapy kosztów
    local_footprint_topic: local_costmap/published_footprint  # Zmieniono z footprint_topic - nowa nazwa topiku śladu robota
    # global_costmap_topic: global_costmap/costmap_raw  # ZAKOMENTOWANO - temap globalnej mapy kosztów
    # global_footprint_topic: global_costmap/published_footprint  # ZAKOMENTOWANO - temat globalnego śladu
    cycle_frequency: 10.0
    behavior_plugins:
      ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: /odometry/filtered  # Zmieniono z global_frame: odom - używa filtrowanej odometrii
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 1.0  # Zmniejszono z 2.0 - krótszy czas symulacji do przodu
    max_rotational_vel: 3.0  # Zwiększono z 1.0 - większa maksymalna prędkość obrotowa
    min_rotational_vel: 1.0  # Zwiększono z 0.4 - większa minimalna prędkość obrotowa
    rotational_acc_lim: 3.2

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered  # Zmieniono z /odom - używa filtrowanej odometrii
    default_nav_to_pose_bt_xml: $(find-pkg-share koala_exploration)/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml  # DODANO - custom behavior tree
    bt_loop_duration: 10
    default_server_timeout: 20

    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 30.0  # Zwiększono z 20.0 - wyższa częstotliwość kontrolera
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: "progress_checker"  # Zmieniono z progress_checker_plugin - nowa nazwa
    goal_checker_plugins: ["goal_checker"]  # Zmieniono z ["general_goal_checker"] - nowa nazwa checkera celu
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::PoseProgressChecker"  # Zmieniono z SimpleProgressChecker - używa sprawdzania pozycji
      required_movement_radius: 0.5
      required_movement_angle: 0.0  # DODANO - wymagany kąt ruchu
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1  # Zmniejszono z 0.25 - mniejsza tolerancja pozycji celu
      yaw_goal_tolerance: 0.1  # Zmniejszono z 0.25 - mniejsza tolerancja orientacji celu
      stateful: True

    # CAŁKOWITA ZMIANA: Zastąpiono DWB kontroler na MPPI kontroler
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"  # Zmieniono z "dwb_core::DWBLocalPlanner" - MPPI zamiast DWB
      time_steps: 56  # NOWY - liczba kroków czasowych dla MPPI
      model_dt: 0.05  # NOWY - krok czasowy modelu
      batch_size: 2000  # NOWY - rozmiar batcha trajektorii
      vx_std: 0.2  # NOWY - odchylenie standardowe prędkości x
      vy_std: 0.2  # NOWY - odchylenie standardowe prędkości y
      wz_std: 0.4  # NOWY - odchylenie standardowe prędkości kątowej
      vx_max: 0.5  # NOWY - maksymalna prędkość x (większa niż 0.26 w DWB)
      vx_min: -0.5  # NOWY - minimalna prędkość x
      vy_max: 0.5  # NOWY - maksymalna prędkość y
      wz_max: 1.9  # NOWY - maksymalna prędkość kątowa (większa niż 1.0 w DWB)
      iteration_count: 1  # NOWY - liczba iteracji MPPI
      prune_distance: 1.7  # NOWY - dystans przycinania trajektorii
      transform_tolerance: 0.1  # Zmniejszono z 0.2 - mniejsza tolerancja transformacji
      temperature: 0.3  # NOWY - temperatura dla MPPI
      gamma: 0.015  # NOWY - współczynnik dyskontowania
      motion_model: "DiffDrive"  # NOWY - model ruchu różnicowego
      visualize: false  # NOWY - wyłączona wizualizacja
      TrajectoryVisualizer:  # NOWY - konfiguracja wizualizatora
        trajectory_step: 5
        time_step: 3
      # NOWY - konfiguracja krytyków MPPI (zastępuje critics z DWB)
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 2
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        forward_preference: true
      VelocityDeadbandCritic:  # NOWY - krtyk martwej strefy prędkości
        enabled: true
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities: [0.05, 0.05, 0.05]
      TwirlingCritic:  # NOWY - krytyk wirowania
        enabled: true
        twirling_cost_power: 1
        twirling_cost_weight: 10.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.1  # DODANO - padding dla footprint
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      #robot_radius: 0.25 # ZAKOMENTOWANO - nie używa się robot_radius
      footprint: "[[0.100, 0.097], [0.100, -0.097], [-0.100, -0.097], [-0.100, 0.097]]"  # DODANO - zastąpiono robot_radius footprintem
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true  # DODANO - czyszczenie na podstawie footprint
        max_obstacle_height: 2.0
        combination_method: 1  # DODANO - metoda kombinowania
        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0  # DODANO - minimalna wysokość przeszkód
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false  # DODANO - wartość inf nie jest poprawna
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true  # DODANO - warstwa włączona
        subscribe_to_updates: true  # DODANO - subskrybuj aktualizacje
        transform_tolerance: 0.1  # DODANO - tolerancja transformacji
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.75  # Zwiększono z 0.55 - większy promień inflacji
        cost_scaling_factor: 2.0  # Zmniejszono z 3.0 - mniejszy współczynnik skalowania kosztu
        inflate_unknown: false  # DODANO - nie napompowuj nieznanego
        inflate_around_unknown: true  # DODANO - napompowuj wokół nieznanego
      always_send_full_costmap: True
      service_introspection_mode: "disabled"  # DODANO - tryb introspekcji serwisu wyłączony

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      footprint_padding: 0.1  # DODANO - padding dla footprint
      footprint: "[[0.100, 0.097], [0.100, -0.097], [-0.100, -0.097], [-0.100, 0.097]]"  # DODANO - zastąpiono robot_radius footprintem
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]  # Zmieniono z ["voxel_layer", "inflation_layer"] - dodano static_layer i obstacle_layer zamiast voxel_layer
      obstacle_layer:  # NOWY - zastąpiono voxel_layer
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false
      static_layer:  # DODANO - nowa warstwa statyczna
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55
        cost_scaling_factor: 10.0  # Zwiększono z 3.0 - większy współczynnik skalowania dla lokalnej mapy
        inflate_unknown: false  # DODANO
        inflate_around_unknown: true  # DODANO

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map.yaml"  # Zmieniono z "" - określono nazwę pliku mapy

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      use_astar: False  
      allow_unknown: True 
      tolerance: 1.0  # Zwiększono z 0.5 - większa tolerancja planera

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

smoother_server:
  ros__parameters:
    use_sim_time: True
    # USUNIĘTO smoother_plugins i simple_smoother - brak konfiguracji wygładzania

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 5.0  # Zmniejszono z 20.0 - niższa częstotliwość wygładzania
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 0.5]  # Zmieniono z [0.26, 0.0, 1.0] - większa prędkość liniowa, mniejsza kątowa
    min_velocity: [-0.5, 0.0, -0.5]  # Zmieniono z [-0.26, 0.0, -1.0] - większa prędkość liniowa wsteczna
    max_accel: [2.0, 0.0, 3.0]  # Zmieniono z [2.5, 0.0, 3.2] - mniejsze przyspieszenie liniowe
    max_decel: [-2.0, 0.0, -3.0]  # Zmieniono z [-2.5, 0.0, -3.2] - mniejsze hamowanie liniowe
    # used in the CLOSED_LOOP feedback mode
    # odom_topic: "odom"  # ZAKOMENTOWANO - nie używa odometrii w trybie otwartej pętli
    # odom_duration: 0.1  # ZAKOMENTOWANO
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0